functionsDirectory = "C:\\Users\\Gebruiker\\Downloads\\Bariq_Autocare\\Bariq\\netlify\\functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
headers = []

[build]
publish = "C:\\Users\\Gebruiker\\Downloads\\Bariq_Autocare\\Bariq\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\Gebruiker\\Downloads\\Bariq_Autocare\\Bariq\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "vite"
port = 8888.0
targetPort = 5173.0

[functions]

[functions.emails]
included_files = ["./emails/**"]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-emails"
pinned_version = "1"

[plugins.inputs]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]